"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Task = { id:string; origin_id:string; origin_name:string; destination_id:string; channel:string; status:string; last_event:string; initial_text:string; created_at:number; updated_at:number };
type EventItem = { id:string; task_id?:string; type:string; direction?:string; reason?:string; error_message?:string; created_at:number };
type Message = { id:string; direction:string; sender_type?:string; text:string; delivery_status:string; created_at:number };
const statusLabel:Record<string,string> = { accepted:"Awaiting event", created:"Created", routing:"Routing", connected:"Connected", ended:"Ended", failed:"Failed" };

export default function Home() {
  const [tasks,setTasks]=useState<Task[]>([]); const [events,setEvents]=useState<EventItem[]>([]); const [messages,setMessages]=useState<Message[]>([]);
  const [selectedId,setSelectedId]=useState(""); const [mode,setMode]=useState<"sandbox"|"live">("sandbox"); const [search,setSearch]=useState("");
  const [composer,setComposer]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({ originId:"customer@example.com",originName:"Maya Chen",destinationId:"support@channel.biz",channel:"my-custom-channel",text:"Hello, I need help with my order.",customerTier:"gold" });

  const refresh=useCallback(async()=>{ const response=await fetch("/api/tasks",{cache:"no-store"}); if(!response.ok)return;
    const data=await response.json() as {tasks:Task[];events:EventItem[];mode:"sandbox"|"live"}; setTasks(data.tasks);setEvents(data.events);setMode(data.mode);setSelectedId(current=>current||data.tasks[0]?.id||""); },[]);
  const loadMessages=useCallback(async(taskId:string)=>{ if(!taskId)return setMessages([]); const response=await fetch(`/api/tasks/${encodeURIComponent(taskId)}/messages`,{cache:"no-store"}); if(response.ok)setMessages((await response.json()).messages as Message[]); },[]);
  useEffect(()=>{const initial=setTimeout(refresh,0);const timer=setInterval(refresh,5000);return()=>{clearTimeout(initial);clearInterval(timer)}},[refresh]);
  useEffect(()=>{const request=setTimeout(()=>loadMessages(selectedId),0);return()=>clearTimeout(request)},[selectedId,loadMessages,events]);
  const selected=tasks.find(task=>task.id===selectedId); const visibleTasks=useMemo(()=>tasks.filter(task=>`${task.origin_name} ${task.origin_id} ${task.id} ${task.status}`.toLowerCase().includes(search.toLowerCase())),[tasks,search]);
  const activeCount=tasks.filter(task=>!["ended","failed"].includes(task.status)).length; const failureCount=tasks.filter(task=>task.status==="failed").length;

  async function createTask(event:FormEvent){event.preventDefault();setBusy(true);setNotice("");const response=await fetch("/api/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await response.json();setBusy(false);
    if(!response.ok)return setNotice(data.error??"Could not create task.");setNotice(mode==="sandbox"?"Sandbox task created. Advance it to simulate Webex lifecycle events.":"Task accepted by Webex. Waiting for task:new or task:failed.");setSelectedId(data.taskId);await refresh();}
  async function appendMessage(event:FormEvent){event.preventDefault();if(!selected||!composer.trim())return;setBusy(true);setNotice("");const response=await fetch(`/api/tasks/${encodeURIComponent(selected.id)}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:composer})});const data=await response.json();setBusy(false);
    if(!response.ok)return setNotice(data.error??"Could not append message.");setComposer("");setNotice("Message accepted. Confirmation arrives through task-message:appended.");await refresh();await loadMessages(selected.id);}
  async function advanceDemo(){if(!selected)return;setBusy(true);const response=await fetch("/api/demo/advance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({taskId:selected.id})});const data=await response.json();setBusy(false);setNotice(response.ok?`Received ${data.type}.`:data.error);await refresh();}

  return <main>
    <header className="topbar"><a className="brand" href="#top" aria-label="Relay home"><span className="brand-mark">R</span><span>Relay</span></a><nav aria-label="Primary"><a className="active" href="#tasks">Tasks</a><a href="#events">Event stream</a><a href="#setup">Setup</a></nav><div className={`mode ${mode}`}><span/>{mode==="live"?"Live Webex":"Sandbox"}</div></header>
    <section className="hero" id="top"><div><p className="eyebrow">CUSTOM MESSAGING MIDDLEWARE</p><h1>One quiet place for every customer conversation.</h1><p className="lede">Create inbound Webex Contact Center tasks, append customer messages, and watch lifecycle webhooks resolve in real time.</p></div><div className="hero-stats"><div><span>Active tasks</span><strong>{String(activeCount).padStart(2,"0")}</strong><small>{tasks.length?"Synced just now":"Ready for first task"}</small></div><div><span>Webhook health</span><strong>{failureCount?"Check":"Good"}</strong><small>{failureCount?`${failureCount} failed task${failureCount>1?"s":""}`:"No failed tasks"}</small></div></div></section>
    <section className="workspace" id="tasks">
      <aside className="task-rail"><div className="section-head"><div><p className="eyebrow">INBOX</p><h2>Tasks</h2></div><span className="count">{tasks.length}</span></div><label className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer or task ID"/></label><div className="task-list">
        {visibleTasks.map(task=><button className={`task-card ${task.id===selectedId?"selected":""}`} key={task.id} onClick={()=>setSelectedId(task.id)}><span className={`status-dot ${task.status}`}/><span className="task-copy"><strong>{task.origin_name||task.origin_id}</strong><small>{task.initial_text}</small><em>{task.channel}</em></span><time>{new Date(task.updated_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></button>)}
        {!visibleTasks.length&&<div className="empty"><span>◇</span><strong>No tasks yet</strong><p>Create your first inbound conversation.</p></div>}</div></aside>
      <section className="conversation">{selected?<><div className="conversation-head"><div><p className="eyebrow">CONVERSATION</p><h2>{selected.origin_name||selected.origin_id}</h2><p>{selected.origin_id} <span>→</span> {selected.destination_id}</p></div><div className={`status-pill ${selected.status}`}>{statusLabel[selected.status]??selected.status}</div></div><div className="task-meta"><span>Task ID</span><code>{selected.id}</code><button onClick={()=>navigator.clipboard?.writeText(selected.id)}>Copy</button></div><div className="timeline">
        {messages.map(message=><article className={`message ${message.direction.toLowerCase()}`} key={message.id}><div className="message-label"><strong>{message.direction==="OUTBOUND"?message.sender_type||"Agent":selected.origin_name||"Customer"}</strong><time>{new Date(message.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></div><p>{message.text||"Attachment"}</p><small>{message.direction==="OUTBOUND"?`Relay: ${message.delivery_status}`:message.id.slice(0,8)}</small></article>)}</div>
        <form className="composer" onSubmit={appendMessage}><textarea value={composer} onChange={e=>setComposer(e.target.value)} placeholder="Append a customer message…" aria-label="Customer message"/><div><span>Sent as inbound customMessaging</span><button disabled={busy||!composer.trim()}>Append message <b>↗</b></button></div></form></>:<div className="select-empty"><span>↗</span><h2>Select a task</h2><p>Conversation details and message history will appear here.</p></div>}</section>
      <aside className="event-rail" id="events"><div className="section-head"><div><p className="eyebrow">LIVE</p><h2>Event stream</h2></div><span className="pulse"/></div><div className="event-list">{events.filter(item=>!selectedId||item.task_id===selectedId).slice(0,14).map(item=><article className="event" key={item.id}><span className={item.type.includes("failed")?"event-icon fail":"event-icon"}>{item.type.includes("message")?"↗":item.type.includes("ended")?"✓":"•"}</span><div><strong>{item.type}</strong><p>{item.error_message||item.reason||(item.direction?`${item.direction.toLowerCase()} event`:"Lifecycle update")}</p><time>{new Date(item.created_at).toLocaleString([],{hour:"2-digit",minute:"2-digit",month:"short",day:"numeric"})}</time></div></article>)}{!events.length&&<div className="empty slim"><span>⋮</span><strong>Listening</strong><p>Webhook events will appear here.</p></div>}</div>{mode==="sandbox"&&selected&&<button className="demo-button" onClick={advanceDemo} disabled={busy||["ended","failed"].includes(selected.status)}>Advance demo event <span>→</span></button>}</aside>
    </section>
    <section className="create-section" id="setup"><div className="create-intro"><p className="eyebrow">NEW INBOUND TASK</p><h2>Start a conversation.</h2><p>The first message creates a task. Later messages are appended to the same task ID.</p><div className="flow-line"><span>External channel</span><b>→</b><span>Relay</span><b>→</b><span>Webex CC</span></div></div><form className="create-form" onSubmit={createTask}>
      <div className="field-row"><label>Customer ID<input required value={form.originId} onChange={e=>setForm({...form,originId:e.target.value})}/></label><label>Customer name<input value={form.originName} onChange={e=>setForm({...form,originName:e.target.value})}/></label></div><div className="field-row"><label>Business address<input required value={form.destinationId} onChange={e=>setForm({...form,destinationId:e.target.value})}/></label><label>Channel name<input required value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}/></label></div><label>Initial customer message<textarea required value={form.text} onChange={e=>setForm({...form,text:e.target.value})}/></label><div className="field-row final-row"><label>Customer tier<input value={form.customerTier} onChange={e=>setForm({...form,customerTier:e.target.value})}/></label><button disabled={busy}>Create task <b>↗</b></button></div>{notice&&<p className="notice" role="status">{notice}</p>}</form></section>
    <footer><span>Relay middleware console</span><span>Webhook endpoint <code>/api/webhooks/webex</code></span></footer>
  </main>;
}
